---
apiVersion: v1
kind: Namespace
metadata:
  name: scaler

---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-scaler-cert
  namespace: scaler
type: kubernetes.io/tls
data:
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3VCZURFeDJMTC9JVEQKaklzL0dmUWkwNHVmKzJYc2NTaW5KQjdHR2FRL0dnODIzZ2JpWmtmMTB2R1VWVzVFR3lBWFNCOEtPWDZVcHlXdwpqbTJvMmlRWlVWc21uYnBNWkgxQTdVSEVmM0ZxTW5DK3h1UmVFUllFSW56VnFSOVRVcFdhdEg3djhaa1pyUXo2CnR6WXlXSm5mWXlBTUFHczVmYnFIRkY2THhpMkg3OERBeDA2NWV0aFVPSDlNM0p4TFlMS1JYeTQvWkp1Rjk5OE8KY2xkZ0xEVk90TDB0K2U3ZjgySHU4NUJjcGx4Y21vU0VuWFZQeUlxY1JsaHJtOVkycVBKcXd4OWJvK0o2MW44RQpqd21wZ1c1V2dmZ1g3MUdsOFNXVkZzdjl1SnhQQW9ieTl5ZzVkTDV4U1NjUTF2ZWVlc0ZWTnlUVTBVZzZBTVd6ClcvQ1BRUldSQWdNQkFBRUNnZ0VBUE9jaHVyeHMveWJvNytjSDlKV0lzNGVGbmYvRnMvSUdZRGhyN0xpY210anIKNmkvYUNQSHl6VDE5L29QSGkxNVM1Tk1BeWZ0RktaRTF4NHlSSkQ3ejAwaDl0ZzROWFI3dUZ3THh1V3RBcmdIcApJMXRJSVFPcHlOaXBCNzJna1BDZUd2NkFUa2tuWTYwRWxkbjR4YlhzWkJtMDVYNWdDRWJRT09ZUUVLclMxSGVtCno3d0NRMWVaVHhmbDdBc3psY0xaL2gwMHpFR1g2ang3TGh6L0VQd21CeEVXYkJYMXo3SE9JaVcrVUFKdmhzcDUKMlJNNm9RL2EvMXNaMEg1a0dJamhaSElZamdsKytrN3l4NVhsT0JXU0xuT0c3T2ZjSFdXd2MyeXo2NHV4c1FZQwpmV245NmVlc0pFSU5PQVdaTW01ZDRTQm1Oa2Y2Sm5NVHpRK3VVd1JSWVFLQmdRRHhsSGpTdURZZ3dtQklEQ2hnCm4rbmNRcDloWWhLQVdPK284TWlsSTBuWE41VStDNWU2MUNiNkFZQjliNENQTXNQY3E1N3JjOFdQTWhxSGtncTMKRFRGQ1ZrVERKdmQ3N1locU9LeHBpeXZZcFRuL3dvTHpSS2owWFpWLzR0NTNZQ1lMbHd6OW5NZEpCN2tINTRCMQppNFFickdUbm9BUmp2cFhJUVYybWVxaDNqd0tCZ1FDNGFSVTUyTXhqajRKd2lNQUdGWGlnTDVoajEwUlBBd1FMCkl6SnZCZ1hxc0hKNkU0TWhmK0hjT3hjWkhOSTZ0Z0VteC9qZkxMUXVhTU9DZ0M3d1M3TTVXZ05aYjZ3cWdWenYKcXRiMndSVVhOZERpUmhRakNBOG9vZUl2dFJCSk9PTTZsWXdhMm1lK1VldTRBWkpSOGdVRkIyYVBkWGZLMzNTeQpuZm15bkhnUTN3S0JnUUNyb2FGSmpDaWdrNWhWOTVWRU9MaXNqUVN3NmoxY3hGTFl3dUM2T2x6K3MzV3JsQTdqClpGQ2d0Q3AyYzU1eG5rNTYyODlYVm5RWWJTOWQvQXJ5ekVPZjdxeUJ2WkI4a21DbG5zZ1hZQkh4cEVtVmhMc0cKWEZSdzhJQURVTXBmSTRkRUdyZlhBdWl1NFBhN1ArVUxIZWpveEUwWUpwNlh3dEtsYUpOQmNNbDV6d0tCZ0d4TgpRcXNEZVIzcmxXYXoyVnA1VjZ0ejZHS1NkVXFWOGRUOHFjenNVNk0rVnl6OHNxR0U4a2VkNkhYV0tGMVVzSjV2CkNPbEEzdHoycUFQSGRrbW5tNjFPQVBPUWt5TXZjRDVOTGd3aTMxa1BRUXJ5cnpiWHI5ZGtJMnR6UWdwT3Y1eVQKWVlJUHpLZklndEJCRkFiT1JVWnJ6ejduZFNBUFZnRGtxRlhPY1BFdkFvR0FkSU9uSjBJZm1lTFV2dFBMWDlzbwoydW52ZlNDTlNzM3QxLzQ4ek1HcysvYktTdkNjZENMMmowRVRvbUZZRGxiUy9ualMzdWllRlpIdjQxclV1TzFRCkZWNTg0aDNHWWhNaVhUZlhkRUphcmNvb0NuMnhQem9mM2ZGSjRhVGticlc5aTZtOGE3aGZra3l3WGtodHJpSEoKQWF4YW9scnFyTHR2VFVrSHpYSkZzNFk9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lVR1VHQ3JsZmo0ZUFOUmhsaG9vV2hmdXNITThNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1Zhemh6TFhOallXeGxjaTV6WTJGc1pYSXVjM1pqTUI0WERUSTFNRFV5TlRFegpNakEwTUZvWERUTTFNRFV5TXpFek1qQTBNRm93SURFZU1Cd0dBMVVFQXd3VmF6aHpMWE5qWVd4bGNpNXpZMkZzClpYSXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyZ1hneE1kaXkveUUKdzR5TFB4bjBJdE9Mbi90bDdIRW9weVFleGhta1B4b1BOdDRHNG1aSDlkTHhsRlZ1UkJzZ0YwZ2ZDamwrbEtjbApzSTV0cU5va0dWRmJKcDI2VEdSOVFPMUJ4SDl4YWpKd3ZzYmtYaEVXQkNKODFha2ZVMUtWbXJSKzcvR1pHYTBNCityYzJNbGlaMzJNZ0RBQnJPWDI2aHhSZWk4WXRoKy9Bd01kT3VYcllWRGgvVE55Y1MyQ3lrVjh1UDJTYmhmZmYKRG5KWFlDdzFUclM5TGZudTMvTmg3dk9RWEtaY1hKcUVoSjExVDhpS25FWllhNXZXTnFqeWFzTWZXNlBpZXRaLwpCSThKcVlGdVZvSDRGKzlScGZFbGxSYkwvYmljVHdLRzh2Y29PWFMrY1VrbkVOYjNubnJCVlRjazFORklPZ0RGCnMxdndqMEVWa1FJREFRQUJvM293ZURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRUF3SUY0REEvQmdOVkhSRUUKT0RBMmdoVnJPSE10YzJOaGJHVnlMbk5qWVd4bGNpNXpkbU9DRVdzNGN5MXpZMkZzWlhJdWMyTmhiR1Z5Z2dwcgpPSE10YzJOaGJHVnlNQjBHQTFVZERnUVdCQlMvUzdXd3RPallSTnkvMGZPNWJaUlg1QndUVERBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFkQ0paRXhyaEdoVDhQZ0l2cVNCWW1XK09SVmNqMDl5ZUdvWHpQL2tRd2tOejJqTXEKd01QTHZVbGo5T0thZ052dDZTTWdGVXh6a2I5dG1lOEJqKzg3OGY1Ums0N3ZVVkZmZjZCL2V6dktwVGM4QTJDZQpRYnkyY2xsUWsxWkxoR0EzYStHTERGZGlPS3RUK3VXMzdzb3JrVHNOODVkbXVGR1VGcmFoejVjWldRUDhKa3l1CklweWp3QzZhVzFYaHd0SzQ4eGdVOXBnK1RhaXgyTDhySkhYa0ZKUytYVFpIL1JJRlF2T1NHcEJwOFE5N1o2SHYKeU82ZWYweG50RUczUEt5Q2QyR1YrV1J4VlhOUFNjbFF5dUQ5VXNXWVlyZytKRHBFMHZqMkVFVld5dUpqcVp5SwpwQzNNSnFUWGRuV2NseXBmTlN4dnhHbVgzWjArdEJObVRPSUc4Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-scaler
  namespace: scaler
spec:
  selector:
    app: k8s-scaler
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-scaler
webhooks:
  - name: SetPodLimitsHook
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: k8s-scaler
        namespace: scaler
        path: "/mutate/pod_limits"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lVR1VHQ3JsZmo0ZUFOUmhsaG9vV2hmdXNITThNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1Zhemh6TFhOallXeGxjaTV6WTJGc1pYSXVjM1pqTUI0WERUSTFNRFV5TlRFegpNakEwTUZvWERUTTFNRFV5TXpFek1qQTBNRm93SURFZU1Cd0dBMVVFQXd3VmF6aHpMWE5qWVd4bGNpNXpZMkZzClpYSXVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyZ1hneE1kaXkveUUKdzR5TFB4bjBJdE9Mbi90bDdIRW9weVFleGhta1B4b1BOdDRHNG1aSDlkTHhsRlZ1UkJzZ0YwZ2ZDamwrbEtjbApzSTV0cU5va0dWRmJKcDI2VEdSOVFPMUJ4SDl4YWpKd3ZzYmtYaEVXQkNKODFha2ZVMUtWbXJSKzcvR1pHYTBNCityYzJNbGlaMzJNZ0RBQnJPWDI2aHhSZWk4WXRoKy9Bd01kT3VYcllWRGgvVE55Y1MyQ3lrVjh1UDJTYmhmZmYKRG5KWFlDdzFUclM5TGZudTMvTmg3dk9RWEtaY1hKcUVoSjExVDhpS25FWllhNXZXTnFqeWFzTWZXNlBpZXRaLwpCSThKcVlGdVZvSDRGKzlScGZFbGxSYkwvYmljVHdLRzh2Y29PWFMrY1VrbkVOYjNubnJCVlRjazFORklPZ0RGCnMxdndqMEVWa1FJREFRQUJvM293ZURBSkJnTlZIUk1FQWpBQU1Bc0dBMVVkRHdRRUF3SUY0REEvQmdOVkhSRUUKT0RBMmdoVnJPSE10YzJOaGJHVnlMbk5qWVd4bGNpNXpkbU9DRVdzNGN5MXpZMkZzWlhJdWMyTmhiR1Z5Z2dwcgpPSE10YzJOaGJHVnlNQjBHQTFVZERnUVdCQlMvUzdXd3RPallSTnkvMGZPNWJaUlg1QndUVERBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFkQ0paRXhyaEdoVDhQZ0l2cVNCWW1XK09SVmNqMDl5ZUdvWHpQL2tRd2tOejJqTXEKd01QTHZVbGo5T0thZ052dDZTTWdGVXh6a2I5dG1lOEJqKzg3OGY1Ums0N3ZVVkZmZjZCL2V6dktwVGM4QTJDZQpRYnkyY2xsUWsxWkxoR0EzYStHTERGZGlPS3RUK3VXMzdzb3JrVHNOODVkbXVGR1VGcmFoejVjWldRUDhKa3l1CklweWp3QzZhVzFYaHd0SzQ4eGdVOXBnK1RhaXgyTDhySkhYa0ZKUytYVFpIL1JJRlF2T1NHcEJwOFE5N1o2SHYKeU82ZWYweG50RUczUEt5Q2QyR1YrV1J4VlhOUFNjbFF5dUQ5VXNXWVlyZytKRHBFMHZqMkVFVld5dUpqcVp5SwpwQzNNSnFUWGRuV2NseXBmTlN4dnhHbVgzWjArdEJObVRPSUc4Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: ["v1"]
    sideEffects: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-scaler
  namespace: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-scaler
  template:
    metadata:
      labels:
        app: k8s-scaler
    spec:
      containers:
        - name: webhook
          image: aphan1um/k8s-python
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /app
              name: appcode
            - name: certs
              mountPath: /app/certs
              readOnly: true
          command:
            - "uvicorn"
          args:
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "443"
            - "--ssl-keyfile"
            - "certs/tls.key"
            - "--ssl-certfile"
            - "certs/tls.crt"
      initContainers:
        - image: alpine/git
          name: alpine-container
          volumeMounts:
            - name: appcode
              mountPath: /app
          command: ["/bin/sh"] 
          args: ["-c", "git clone --depth=1 
                    https://github.com/aphan1um/DeathStarBench.git /DeathStarBench &&
                    cp -r /DeathStarBench/custom/k8s-scaler/app/* /app"]
      volumes:
      - name: appcode
        emptyDir: {}
      - name: certs
        secret:
          secretName: k8s-scaler-cert
