apiVersion: v1
kind: Pod
metadata:
  labels:
    run: load-test
  name: load-test
spec:
  containers:
    - args: ["/bin/sh", "-c", "sleep 365d"]
      volumeMounts:
        - mountPath: /scripts
          name: scripts
      image: aphan1um/wrk2-social-network
      imagePullPolicy: Always
      name: load-test
  initContainers:
    - image: alpine/git
      name: alpine-container
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      command: ["/bin/sh"] 
      args: ["-c", "git clone --depth=1 
                https://gitlab.engr.illinois.edu/DEPEND/firm.git /DeathStarBench &&
                cp -r /DeathStarBench/socialNetwork/wrk2/* /scripts/socialNetwork"]
  restartPolicy: Never
  tolerations:
    - effect: NoSchedule
      key: is-monitor
      operator: Exists
  volumes:
  - name: scripts
    emptyDir: {}
