apiVersion: v1
kind: Pod
metadata:
  labels:
    run: load-test
  name: load-test
spec:
  containers:
    - args: ["/bin/sh", "-c", "sleep 365d"]
      env:
        - name: service_hostname
          value: nginx-thrift
      volumeMounts:
        - mountPath: /scripts
          name: scripts
      image: aphan1um/wrk2-social-network
      imagePullPolicy: Always
      name: load-test
  initContainers:
    - image: alpine/git
      name: alpine-container
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      command: ["/bin/sh"] 
      args: ["-c", "git clone --depth=1 
                https://github.com/aphan1um/DeathStarBench.git /DeathStarBench &&
                cp -r /DeathStarBench/socialNetwork/wrk2/* /scripts/socialNetwork"]
  restartPolicy: Never
  # tolerations:
  #   - effect: NoSchedule
  #     key: wrk2
  #     operator: Exists
  volumes:
  - name: scripts
    emptyDir: {}