---
apiVersion: v1
kind: Namespace
metadata:
  name: scaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding-rbac-scaler
subjects:
  - kind: ServiceAccount
    name: default
    namespace: scaler
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
