apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-webhook
  template:
    metadata:
      labels:
        app: k8s-webhook
    spec:
      containers:
        - name: webhook
          image: aphan1um/k8s-python
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /app
              name: appcode
          command:
            - "uvicorn"
          args:
            - "webhook:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "443"
      initContainers:
        - image: alpine/git
          name: alpine-container
          volumeMounts:
            - name: appcode
              mountPath: /app
          command: ["/bin/sh"] 
          args: ["-c", "git clone --depth=1 
                    https://github.com/aphan1um/DeathStarBench.git /DeathStarBench &&
                    cp -r /DeathStarBench/custom/k8s-webhook/app/* /app"]
